//
//Akeyless API
//
//The purpose of this application is to provide access to Akeyless API.
//
//The version of the OpenAPI document: 2.0
//
//Contact: support@akeyless.io
//
//Generated by OpenAPI Generator: https://openapi-generator.tech

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.24.4
// source: models/target_name_with_hosts.proto

package akeyless_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TargetNameWithHosts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hosts      []string `protobuf:"bytes,99467211,rep,name=hosts,proto3" json:"hosts,omitempty"`
	TargetName string   `protobuf:"bytes,474147722,opt,name=target_name,proto3" json:"target_name,omitempty"`
}

func (x *TargetNameWithHosts) Reset() {
	*x = TargetNameWithHosts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_target_name_with_hosts_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TargetNameWithHosts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetNameWithHosts) ProtoMessage() {}

func (x *TargetNameWithHosts) ProtoReflect() protoreflect.Message {
	mi := &file_models_target_name_with_hosts_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetNameWithHosts.ProtoReflect.Descriptor instead.
func (*TargetNameWithHosts) Descriptor() ([]byte, []int) {
	return file_models_target_name_with_hosts_proto_rawDescGZIP(), []int{0}
}

func (x *TargetNameWithHosts) GetHosts() []string {
	if x != nil {
		return x.Hosts
	}
	return nil
}

func (x *TargetNameWithHosts) GetTargetName() string {
	if x != nil {
		return x.TargetName
	}
	return ""
}

var File_models_target_name_with_hosts_proto protoreflect.FileDescriptor

var file_models_target_name_with_hosts_proto_rawDesc = []byte{
	0x0a, 0x23, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x77, 0x69, 0x74, 0x68, 0x5f, 0x68, 0x6f, 0x73, 0x74, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x61, 0x6b, 0x65, 0x79, 0x6c, 0x65, 0x73, 0x73, 0x5f,
	0x67, 0x72, 0x70, 0x63, 0x1a, 0x1a, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x73, 0x70, 0x65,
	0x63, 0x69, 0x61, 0x6c, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x54, 0x0a, 0x13, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x57, 0x69,
	0x74, 0x68, 0x48, 0x6f, 0x73, 0x74, 0x73, 0x12, 0x17, 0x0a, 0x05, 0x68, 0x6f, 0x73, 0x74, 0x73,
	0x18, 0xcb, 0xff, 0xb6, 0x2f, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x68, 0x6f, 0x73, 0x74, 0x73,
	0x12, 0x24, 0x0a, 0x0b, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x8a, 0xd7, 0x8b, 0xe2, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x51, 0x0a, 0x11, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x6b,
	0x65, 0x79, 0x6c, 0x65, 0x73, 0x73, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x50, 0x01, 0x5a, 0x0f, 0x2e,
	0x3b, 0x61, 0x6b, 0x65, 0x79, 0x6c, 0x65, 0x73, 0x73, 0x5f, 0x67, 0x72, 0x70, 0x63, 0xaa, 0x02,
	0x0d, 0x41, 0x6b, 0x65, 0x79, 0x6c, 0x65, 0x73, 0x73, 0x2e, 0x47, 0x72, 0x70, 0x63, 0xca, 0x02,
	0x0d, 0x41, 0x6b, 0x65, 0x79, 0x6c, 0x65, 0x73, 0x73, 0x5c, 0x67, 0x52, 0x50, 0x43, 0xe2, 0x02,
	0x08, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x50, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_models_target_name_with_hosts_proto_rawDescOnce sync.Once
	file_models_target_name_with_hosts_proto_rawDescData = file_models_target_name_with_hosts_proto_rawDesc
)

func file_models_target_name_with_hosts_proto_rawDescGZIP() []byte {
	file_models_target_name_with_hosts_proto_rawDescOnce.Do(func() {
		file_models_target_name_with_hosts_proto_rawDescData = protoimpl.X.CompressGZIP(file_models_target_name_with_hosts_proto_rawDescData)
	})
	return file_models_target_name_with_hosts_proto_rawDescData
}

var file_models_target_name_with_hosts_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_models_target_name_with_hosts_proto_goTypes = []any{
	(*TargetNameWithHosts)(nil), // 0: akeyless_grpc.TargetNameWithHosts
}
var file_models_target_name_with_hosts_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_models_target_name_with_hosts_proto_init() }
func file_models_target_name_with_hosts_proto_init() {
	if File_models_target_name_with_hosts_proto != nil {
		return
	}
	file_models_special_types_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_models_target_name_with_hosts_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*TargetNameWithHosts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_models_target_name_with_hosts_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_target_name_with_hosts_proto_goTypes,
		DependencyIndexes: file_models_target_name_with_hosts_proto_depIdxs,
		MessageInfos:      file_models_target_name_with_hosts_proto_msgTypes,
	}.Build()
	File_models_target_name_with_hosts_proto = out.File
	file_models_target_name_with_hosts_proto_rawDesc = nil
	file_models_target_name_with_hosts_proto_goTypes = nil
	file_models_target_name_with_hosts_proto_depIdxs = nil
}
