//
//Akeyless API
//
//The purpose of this application is to provide access to Akeyless API.
//
//The version of the OpenAPI document: 2.0
//
//Contact: support@akeyless.io
//
//Generated by OpenAPI Generator: https://openapi-generator.tech

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.24.4
// source: models/auth_output.proto

package akeyless_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Creds *SystemAccessCredentialsReplyObj `protobuf:"bytes,94925029,opt,name=creds,proto3" json:"creds,omitempty"`
	Token string                           `protobuf:"bytes,110541305,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *AuthOutput) Reset() {
	*x = AuthOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_auth_output_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthOutput) ProtoMessage() {}

func (x *AuthOutput) ProtoReflect() protoreflect.Message {
	mi := &file_models_auth_output_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthOutput.ProtoReflect.Descriptor instead.
func (*AuthOutput) Descriptor() ([]byte, []int) {
	return file_models_auth_output_proto_rawDescGZIP(), []int{0}
}

func (x *AuthOutput) GetCreds() *SystemAccessCredentialsReplyObj {
	if x != nil {
		return x.Creds
	}
	return nil
}

func (x *AuthOutput) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_models_auth_output_proto protoreflect.FileDescriptor

var file_models_auth_output_proto_rawDesc = []byte{
	0x0a, 0x18, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x6f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x61, 0x6b, 0x65, 0x79,
	0x6c, 0x65, 0x73, 0x73, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x1a, 0x1a, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x73, 0x2f, 0x73, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x30, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x73, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x5f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x63, 0x72, 0x65, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x5f, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x5f, 0x6f, 0x62,
	0x6a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6e, 0x0a, 0x0a, 0x41, 0x75, 0x74, 0x68, 0x4f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x47, 0x0a, 0x05, 0x63, 0x72, 0x65, 0x64, 0x73, 0x18, 0xe5,
	0xe1, 0xa1, 0x2d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x61, 0x6b, 0x65, 0x79, 0x6c, 0x65,
	0x73, 0x73, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x41, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x4f, 0x62, 0x6a, 0x52, 0x05, 0x63, 0x72, 0x65, 0x64, 0x73, 0x12, 0x17,
	0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0xf9, 0xf3, 0xda, 0x34, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x42, 0x51, 0x0a, 0x11, 0x63, 0x6f, 0x6d, 0x2e, 0x61,
	0x6b, 0x65, 0x79, 0x6c, 0x65, 0x73, 0x73, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x50, 0x01, 0x5a, 0x0f,
	0x2e, 0x3b, 0x61, 0x6b, 0x65, 0x79, 0x6c, 0x65, 0x73, 0x73, 0x5f, 0x67, 0x72, 0x70, 0x63, 0xaa,
	0x02, 0x0d, 0x41, 0x6b, 0x65, 0x79, 0x6c, 0x65, 0x73, 0x73, 0x2e, 0x47, 0x72, 0x70, 0x63, 0xca,
	0x02, 0x0d, 0x41, 0x6b, 0x65, 0x79, 0x6c, 0x65, 0x73, 0x73, 0x5c, 0x67, 0x52, 0x50, 0x43, 0xe2,
	0x02, 0x08, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x50, 0x00, 0x50, 0x01, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_models_auth_output_proto_rawDescOnce sync.Once
	file_models_auth_output_proto_rawDescData = file_models_auth_output_proto_rawDesc
)

func file_models_auth_output_proto_rawDescGZIP() []byte {
	file_models_auth_output_proto_rawDescOnce.Do(func() {
		file_models_auth_output_proto_rawDescData = protoimpl.X.CompressGZIP(file_models_auth_output_proto_rawDescData)
	})
	return file_models_auth_output_proto_rawDescData
}

var file_models_auth_output_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_models_auth_output_proto_goTypes = []any{
	(*AuthOutput)(nil),                      // 0: akeyless_grpc.AuthOutput
	(*SystemAccessCredentialsReplyObj)(nil), // 1: akeyless_grpc.SystemAccessCredentialsReplyObj
}
var file_models_auth_output_proto_depIdxs = []int32{
	1, // 0: akeyless_grpc.AuthOutput.creds:type_name -> akeyless_grpc.SystemAccessCredentialsReplyObj
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_models_auth_output_proto_init() }
func file_models_auth_output_proto_init() {
	if File_models_auth_output_proto != nil {
		return
	}
	file_models_special_types_proto_init()
	file_models_system_access_credentials_reply_obj_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_models_auth_output_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*AuthOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_models_auth_output_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_auth_output_proto_goTypes,
		DependencyIndexes: file_models_auth_output_proto_depIdxs,
		MessageInfos:      file_models_auth_output_proto_msgTypes,
	}.Build()
	File_models_auth_output_proto = out.File
	file_models_auth_output_proto_rawDesc = nil
	file_models_auth_output_proto_goTypes = nil
	file_models_auth_output_proto_depIdxs = nil
}
