//
//Akeyless API
//
//The purpose of this application is to provide access to Akeyless API.
//
//The version of the OpenAPI document: 2.0
//
//Contact: support@akeyless.io
//
//Generated by OpenAPI Generator: https://openapi-generator.tech

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.24.4
// source: models/email_tokenizer_info.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmailTokenizerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// What length of a random domain suffix to generate used only if FixedDomainSuffix is empty
	DomainSuffixLength int64 `protobuf:"varint,260543321,opt,name=domain_suffix_length,proto3" json:"domain_suffix_length,omitempty"`
	// if FixedDomainSuffix isn't empty, it will be appended to the output
	FixedDomainSuffix string `protobuf:"bytes,529360481,opt,name=fixed_domain_suffix,proto3" json:"fixed_domain_suffix,omitempty"`
	// How many letters of the plaintext to keep in the output
	KeepPrefixLength int64 `protobuf:"varint,153104904,opt,name=keep_prefix_length,proto3" json:"keep_prefix_length,omitempty"`
}

func (x *EmailTokenizerInfo) Reset() {
	*x = EmailTokenizerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_email_tokenizer_info_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmailTokenizerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailTokenizerInfo) ProtoMessage() {}

func (x *EmailTokenizerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_models_email_tokenizer_info_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailTokenizerInfo.ProtoReflect.Descriptor instead.
func (*EmailTokenizerInfo) Descriptor() ([]byte, []int) {
	return file_models_email_tokenizer_info_proto_rawDescGZIP(), []int{0}
}

func (x *EmailTokenizerInfo) GetDomainSuffixLength() int64 {
	if x != nil {
		return x.DomainSuffixLength
	}
	return 0
}

func (x *EmailTokenizerInfo) GetFixedDomainSuffix() string {
	if x != nil {
		return x.FixedDomainSuffix
	}
	return ""
}

func (x *EmailTokenizerInfo) GetKeepPrefixLength() int64 {
	if x != nil {
		return x.KeepPrefixLength
	}
	return 0
}

var File_models_email_tokenizer_info_proto protoreflect.FileDescriptor

var file_models_email_tokenizer_info_proto_rawDesc = []byte{
	0x0a, 0x21, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x69, 0x7a, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x61, 0x6b, 0x65, 0x79, 0x6c, 0x65, 0x73, 0x73, 0x5f, 0x67, 0x72,
	0x70, 0x63, 0x1a, 0x1a, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x73, 0x70, 0x65, 0x63, 0x69,
	0x61, 0x6c, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb4,
	0x01, 0x0a, 0x12, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x69, 0x7a, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x35, 0x0a, 0x14, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x5f,
	0x73, 0x75, 0x66, 0x66, 0x69, 0x78, 0x5f, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0xd9, 0xa6,
	0x9e, 0x7c, 0x20, 0x01, 0x28, 0x03, 0x52, 0x14, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x5f, 0x73,
	0x75, 0x66, 0x66, 0x69, 0x78, 0x5f, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x34, 0x0a, 0x13,
	0x66, 0x69, 0x78, 0x65, 0x64, 0x5f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x5f, 0x73, 0x75, 0x66,
	0x66, 0x69, 0x78, 0x18, 0xe1, 0xcc, 0xb5, 0xfc, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x66,
	0x69, 0x78, 0x65, 0x64, 0x5f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x5f, 0x73, 0x75, 0x66, 0x66,
	0x69, 0x78, 0x12, 0x31, 0x0a, 0x12, 0x6b, 0x65, 0x65, 0x70, 0x5f, 0x70, 0x72, 0x65, 0x66, 0x69,
	0x78, 0x5f, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x88, 0xe4, 0x80, 0x49, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x12, 0x6b, 0x65, 0x65, 0x70, 0x5f, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x5f, 0x6c,
	0x65, 0x6e, 0x67, 0x74, 0x68, 0x42, 0x51, 0x0a, 0x11, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x6b, 0x65,
	0x79, 0x6c, 0x65, 0x73, 0x73, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x50, 0x01, 0x5a, 0x0f, 0x2e, 0x3b,
	0x61, 0x6b, 0x65, 0x79, 0x6c, 0x65, 0x73, 0x73, 0x5f, 0x67, 0x72, 0x70, 0x63, 0xaa, 0x02, 0x0d,
	0x41, 0x6b, 0x65, 0x79, 0x6c, 0x65, 0x73, 0x73, 0x2e, 0x47, 0x72, 0x70, 0x63, 0xca, 0x02, 0x0d,
	0x41, 0x6b, 0x65, 0x79, 0x6c, 0x65, 0x73, 0x73, 0x5c, 0x67, 0x52, 0x50, 0x43, 0xe2, 0x02, 0x08,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x50, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_models_email_tokenizer_info_proto_rawDescOnce sync.Once
	file_models_email_tokenizer_info_proto_rawDescData = file_models_email_tokenizer_info_proto_rawDesc
)

func file_models_email_tokenizer_info_proto_rawDescGZIP() []byte {
	file_models_email_tokenizer_info_proto_rawDescOnce.Do(func() {
		file_models_email_tokenizer_info_proto_rawDescData = protoimpl.X.CompressGZIP(file_models_email_tokenizer_info_proto_rawDescData)
	})
	return file_models_email_tokenizer_info_proto_rawDescData
}

var file_models_email_tokenizer_info_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_models_email_tokenizer_info_proto_goTypes = []any{
	(*EmailTokenizerInfo)(nil), // 0: akeyless_grpc.EmailTokenizerInfo
}
var file_models_email_tokenizer_info_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_models_email_tokenizer_info_proto_init() }
func file_models_email_tokenizer_info_proto_init() {
	if File_models_email_tokenizer_info_proto != nil {
		return
	}
	file_models_special_types_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_models_email_tokenizer_info_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*EmailTokenizerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_models_email_tokenizer_info_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_email_tokenizer_info_proto_goTypes,
		DependencyIndexes: file_models_email_tokenizer_info_proto_depIdxs,
		MessageInfos:      file_models_email_tokenizer_info_proto_msgTypes,
	}.Build()
	File_models_email_tokenizer_info_proto = out.File
	file_models_email_tokenizer_info_proto_rawDesc = nil
	file_models_email_tokenizer_info_proto_goTypes = nil
	file_models_email_tokenizer_info_proto_depIdxs = nil
}
