//
//Akeyless API
//
//The purpose of this application is to provide access to Akeyless API.
//
//The version of the OpenAPI document: 2.0
//
//Contact: support@akeyless.io
//
//Generated by OpenAPI Generator: https://openapi-generator.tech

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.24.4
// source: models/get_secret_value.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSecretValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// for personal password manager
	Accessibility string `protobuf:"bytes,213139122,opt,name=accessibility,proto3" json:"accessibility,omitempty"`
	// Retrieve the Secret value without checking the Gateway's cache [true/false]. This flag is only relevant when using the RestAPI
	IgnoreCache string `protobuf:"bytes,459170874,opt,name=ignore_cache,json=ignore-cache,proto3" json:"ignore_cache,omitempty"`
	// Set output format to JSON
	Json bool `protobuf:"varint,3271912,opt,name=json,proto3" json:"json,omitempty"`
	// Secret name
	Names []string `protobuf:"bytes,104585032,rep,name=names,proto3" json:"names,omitempty"`
	// Print the secret value with json-pretty-print (not relevent to SDK)
	PrettyPrint bool `protobuf:"varint,510656876,opt,name=pretty_print,json=pretty-print,proto3" json:"pretty_print,omitempty"`
	// Authentication token (see `/auth` and `/configure`)
	Token string `protobuf:"bytes,110541305,opt,name=token,proto3" json:"token,omitempty"`
	// The universal identity token, Required only for universal_identity authentication
	UidToken string `protobuf:"bytes,468850238,opt,name=uid_token,json=uid-token,proto3" json:"uid_token,omitempty"`
	// Secret version, if negative value N is provided the last N versions will return (maximum 20)
	Version int32 `protobuf:"varint,351608024,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *GetSecretValue) Reset() {
	*x = GetSecretValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_get_secret_value_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSecretValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretValue) ProtoMessage() {}

func (x *GetSecretValue) ProtoReflect() protoreflect.Message {
	mi := &file_models_get_secret_value_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretValue.ProtoReflect.Descriptor instead.
func (*GetSecretValue) Descriptor() ([]byte, []int) {
	return file_models_get_secret_value_proto_rawDescGZIP(), []int{0}
}

func (x *GetSecretValue) GetAccessibility() string {
	if x != nil {
		return x.Accessibility
	}
	return ""
}

func (x *GetSecretValue) GetIgnoreCache() string {
	if x != nil {
		return x.IgnoreCache
	}
	return ""
}

func (x *GetSecretValue) GetJson() bool {
	if x != nil {
		return x.Json
	}
	return false
}

func (x *GetSecretValue) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *GetSecretValue) GetPrettyPrint() bool {
	if x != nil {
		return x.PrettyPrint
	}
	return false
}

func (x *GetSecretValue) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetSecretValue) GetUidToken() string {
	if x != nil {
		return x.UidToken
	}
	return ""
}

func (x *GetSecretValue) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_models_get_secret_value_proto protoreflect.FileDescriptor

var file_models_get_secret_value_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x67, 0x65, 0x74, 0x5f, 0x73, 0x65, 0x63,
	0x72, 0x65, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0d, 0x61, 0x6b, 0x65, 0x79, 0x6c, 0x65, 0x73, 0x73, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x1a, 0x1a,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x73, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x92, 0x02, 0x0a, 0x0e, 0x47,
	0x65, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x27, 0x0a,
	0x0d, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x18, 0xb2,
	0xfd, 0xd0, 0x65, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x69,
	0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x26, 0x0a, 0x0c, 0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65,
	0x5f, 0x63, 0x61, 0x63, 0x68, 0x65, 0x18, 0xba, 0xc8, 0xf9, 0xda, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x2d, 0x63, 0x61, 0x63, 0x68, 0x65, 0x12, 0x15,
	0x0a, 0x04, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0xe8, 0xd9, 0xc7, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x04, 0x6a, 0x73, 0x6f, 0x6e, 0x12, 0x17, 0x0a, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0xc8,
	0xae, 0xef, 0x31, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x26,
	0x0a, 0x0c, 0x70, 0x72, 0x65, 0x74, 0x74, 0x79, 0x5f, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x18, 0xec,
	0x82, 0xc0, 0xf3, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x70, 0x72, 0x65, 0x74, 0x74, 0x79,
	0x2d, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x12, 0x17, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0xf9, 0xf3, 0xda, 0x34, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12,
	0x20, 0x0a, 0x09, 0x75, 0x69, 0x64, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0xbe, 0xac, 0xc8,
	0xdf, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x69, 0x64, 0x2d, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x1c, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0xd8, 0xb9, 0xd4,
	0xa7, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x42,
	0x51, 0x0a, 0x11, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x6b, 0x65, 0x79, 0x6c, 0x65, 0x73, 0x73, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x50, 0x01, 0x5a, 0x0f, 0x2e, 0x3b, 0x61, 0x6b, 0x65, 0x79, 0x6c, 0x65,
	0x73, 0x73, 0x5f, 0x67, 0x72, 0x70, 0x63, 0xaa, 0x02, 0x0d, 0x41, 0x6b, 0x65, 0x79, 0x6c, 0x65,
	0x73, 0x73, 0x2e, 0x47, 0x72, 0x70, 0x63, 0xca, 0x02, 0x0d, 0x41, 0x6b, 0x65, 0x79, 0x6c, 0x65,
	0x73, 0x73, 0x5c, 0x67, 0x52, 0x50, 0x43, 0xe2, 0x02, 0x08, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x50, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_models_get_secret_value_proto_rawDescOnce sync.Once
	file_models_get_secret_value_proto_rawDescData = file_models_get_secret_value_proto_rawDesc
)

func file_models_get_secret_value_proto_rawDescGZIP() []byte {
	file_models_get_secret_value_proto_rawDescOnce.Do(func() {
		file_models_get_secret_value_proto_rawDescData = protoimpl.X.CompressGZIP(file_models_get_secret_value_proto_rawDescData)
	})
	return file_models_get_secret_value_proto_rawDescData
}

var file_models_get_secret_value_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_models_get_secret_value_proto_goTypes = []any{
	(*GetSecretValue)(nil), // 0: akeyless_grpc.GetSecretValue
}
var file_models_get_secret_value_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_models_get_secret_value_proto_init() }
func file_models_get_secret_value_proto_init() {
	if File_models_get_secret_value_proto != nil {
		return
	}
	file_models_special_types_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_models_get_secret_value_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetSecretValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_models_get_secret_value_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_get_secret_value_proto_goTypes,
		DependencyIndexes: file_models_get_secret_value_proto_depIdxs,
		MessageInfos:      file_models_get_secret_value_proto_msgTypes,
	}.Build()
	File_models_get_secret_value_proto = out.File
	file_models_get_secret_value_proto_rawDesc = nil
	file_models_get_secret_value_proto_goTypes = nil
	file_models_get_secret_value_proto_depIdxs = nil
}
