//
//Akeyless API
//
//The purpose of this application is to provide access to Akeyless API.
//
//The version of the OpenAPI document: 2.0
//
//Contact: support@akeyless.io
//
//Generated by OpenAPI Generator: https://openapi-generator.tech

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.24.4
// source: models/list_items_in_path_output.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListItemsInPathOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Folders  []string `protobuf:"bytes,146378300,rep,name=folders,proto3" json:"folders,omitempty"`
	Items    []*Item  `protobuf:"bytes,100526016,rep,name=items,proto3" json:"items,omitempty"`
	NextPage string   `protobuf:"bytes,143355997,opt,name=next_page,proto3" json:"next_page,omitempty"`
}

func (x *ListItemsInPathOutput) Reset() {
	*x = ListItemsInPathOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_list_items_in_path_output_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListItemsInPathOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemsInPathOutput) ProtoMessage() {}

func (x *ListItemsInPathOutput) ProtoReflect() protoreflect.Message {
	mi := &file_models_list_items_in_path_output_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemsInPathOutput.ProtoReflect.Descriptor instead.
func (*ListItemsInPathOutput) Descriptor() ([]byte, []int) {
	return file_models_list_items_in_path_output_proto_rawDescGZIP(), []int{0}
}

func (x *ListItemsInPathOutput) GetFolders() []string {
	if x != nil {
		return x.Folders
	}
	return nil
}

func (x *ListItemsInPathOutput) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListItemsInPathOutput) GetNextPage() string {
	if x != nil {
		return x.NextPage
	}
	return ""
}

var File_models_list_items_in_path_output_proto protoreflect.FileDescriptor

var file_models_list_items_in_path_output_proto_rawDesc = []byte{
	0x0a, 0x26, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x5f, 0x69, 0x6e, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x5f, 0x6f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x61, 0x6b, 0x65, 0x79, 0x6c, 0x65,
	0x73, 0x73, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x1a, 0x1a, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f,
	0x73, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x69, 0x74, 0x65, 0x6d,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x83, 0x01, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x49,
	0x74, 0x65, 0x6d, 0x73, 0x49, 0x6e, 0x50, 0x61, 0x74, 0x68, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74,
	0x12, 0x1b, 0x0a, 0x07, 0x66, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x73, 0x18, 0xbc, 0x9c, 0xe6, 0x45,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x66, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x73, 0x12, 0x2c, 0x0a,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0xc0, 0xcf, 0xf7, 0x2f, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x61, 0x6b, 0x65, 0x79, 0x6c, 0x65, 0x73, 0x73, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x1f, 0x0a, 0x09, 0x6e,
	0x65, 0x78, 0x74, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x18, 0xdd, 0xe0, 0xad, 0x44, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x42, 0x51, 0x0a, 0x11,
	0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x6b, 0x65, 0x79, 0x6c, 0x65, 0x73, 0x73, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x50, 0x01, 0x5a, 0x0f, 0x2e, 0x3b, 0x61, 0x6b, 0x65, 0x79, 0x6c, 0x65, 0x73, 0x73, 0x5f,
	0x67, 0x72, 0x70, 0x63, 0xaa, 0x02, 0x0d, 0x41, 0x6b, 0x65, 0x79, 0x6c, 0x65, 0x73, 0x73, 0x2e,
	0x47, 0x72, 0x70, 0x63, 0xca, 0x02, 0x0d, 0x41, 0x6b, 0x65, 0x79, 0x6c, 0x65, 0x73, 0x73, 0x5c,
	0x67, 0x52, 0x50, 0x43, 0xe2, 0x02, 0x08, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x50,
	0x00, 0x50, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_models_list_items_in_path_output_proto_rawDescOnce sync.Once
	file_models_list_items_in_path_output_proto_rawDescData = file_models_list_items_in_path_output_proto_rawDesc
)

func file_models_list_items_in_path_output_proto_rawDescGZIP() []byte {
	file_models_list_items_in_path_output_proto_rawDescOnce.Do(func() {
		file_models_list_items_in_path_output_proto_rawDescData = protoimpl.X.CompressGZIP(file_models_list_items_in_path_output_proto_rawDescData)
	})
	return file_models_list_items_in_path_output_proto_rawDescData
}

var file_models_list_items_in_path_output_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_models_list_items_in_path_output_proto_goTypes = []any{
	(*ListItemsInPathOutput)(nil), // 0: akeyless_grpc.ListItemsInPathOutput
	(*Item)(nil),                  // 1: akeyless_grpc.Item
}
var file_models_list_items_in_path_output_proto_depIdxs = []int32{
	1, // 0: akeyless_grpc.ListItemsInPathOutput.items:type_name -> akeyless_grpc.Item
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_models_list_items_in_path_output_proto_init() }
func file_models_list_items_in_path_output_proto_init() {
	if File_models_list_items_in_path_output_proto != nil {
		return
	}
	file_models_special_types_proto_init()
	file_models_item_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_models_list_items_in_path_output_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ListItemsInPathOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_models_list_items_in_path_output_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_list_items_in_path_output_proto_goTypes,
		DependencyIndexes: file_models_list_items_in_path_output_proto_depIdxs,
		MessageInfos:      file_models_list_items_in_path_output_proto_msgTypes,
	}.Build()
	File_models_list_items_in_path_output_proto = out.File
	file_models_list_items_in_path_output_proto_rawDesc = nil
	file_models_list_items_in_path_output_proto_goTypes = nil
	file_models_list_items_in_path_output_proto_depIdxs = nil
}
